CREATE TABLE test_types (
    `bit` bit,
    `tinyint` tinyint,
    `smallint` smallint,
    `mediumint` mediumint,
    `int` int,
    `integer` integer,
    `bigint` bigint,
    `real` real,
    `double` double,
    `float` float,
    `decimal` decimal,
    `numeric` numeric,
    `char` char,
    `varchar` varchar(255),
    `date` date,
    `time` time,
    `year` year,
    `timestamp` timestamp,
    `datetime` datetime,
    `tinyblob` tinyblob,
    `blob` blob,
    `mediumblob` mediumblob,
    `longblob` longblob,
    `tinytext` tinytext,
    `text` text,
    `mediumtext` mediumtext,
    `longtext` longtext,
    `enum` enum('value1', 'value2', 'value3'),
    `set` set('value1', 'value2', 'value3'),
    `binary` binary,
    `varbinary` varbinary(1024),
    `point` point,
    `linestring` linestring,
    `polygon` polygon,
    `geometry` geometry,
    `multipoint` multipoint,
    `multilinestring` multilinestring,
    `multipolygon` multipolygon,
    `geometrycollection` geometrycollection
);